### PR TITLE
add temporary mailchimp form on homepage

### PR DESCRIPTION
**Pull request by gsambrotta**

### CODE REVIEW

**Comment by xMartin** [comment]
You still want this? This is really prominent.

**Comment by Ivoz** [comment]
Needs updating w.r.t sass as well if so

**Comment by xMartin** [comment]
@gsambrotta What's the status of this? Please close if not needed any more.

**Comment by gsambrotta** [comment]
@xMartin it was for get newsletter subscibers. No needed anymore

**Pull request closed without merging**
