### PR TITLE
remove top menu

### PR DESCRIPTION
**Pull request by gsambrotta**
We decided to remove the top menu because it was just a repetition of footer and it was broken on narrow screen size.
Also users cannot easily go back to home page just by clicking on logo.

The co-learning Frontend Group

### CODE REVIEW

**Comment by lehmannro** [comment]
Is there maybe a way to _fix_ the menu instead of removing it?  I think having a footer as the sole way of navigation is somewhat odd and at least uncommon.

**Comment by gsambrotta** [comment]
Maybe I express my self wrong, we didn't mean the whole top menu! Of'course we need a top navigation. We meant the second menu, the one you open clicking on the arrow and show all the chapters we have and some others links that we already show in the main top menu.

**Comment by gsambrotta** [comment]
BEFORE MERGE: Clean up also style related to the menu!

**Comment by bastianalbers** [comment]
Let me fix that menu for narrow screens now, or are you on it? Bring back the burger for the small screen?

**Comment by gsambrotta** [comment]
We remove it the menu so.. no need to fix for narrow screen anymore :)

**Comment by bastianalbers** [comment]
Well, yes, i was also completely for that...but! This is not ideal:
ots-narrow
Let me propose a fix for that...

**Pull request merged**
