### PR TITLE
berlin: add twitter and facebook link to about

### PR DESCRIPTION
**Pull request by xMartin**
currently we don't have any link to facebook (berlin page) and the twitter widget is quite far down in the page

### CODE REVIEW

**Comment by lehmannro** [comment]
I'd suggest tweaking the master layout so that all chapters can profit from this.

**Comment by xMartin** [comment]
@lehmannro not sure if any other chapter has a facebook page, but sure. let's open an issue for that.

**Comment by bastianalbers** [comment]
I'm happy to merge as is and suggest to do the master layout change in a different PR.

**Comment by lehmannro** [comment]
:+1:   Don't forget to remove this in the other PR then.

**Pull request merged**
