### PR TITLE
Optimizes image file sizes

### PR DESCRIPTION
**Pull request by mbesser**
I've noticed that there are some really heavy image files on the website. Especially the header images for each OTS chapter had some huge potential for optimization.

**Technique** (which is relatively popular) used to achieve smaller file sizes while keeping the perceived image quality relatively high:
- increase the dimensions of each image
- save as highly compressed jpeg file
- use ImageOptim to squeeze out some extra KBs

**The Effect:**
By doing this i was able to reduce the weight of the Berlin page from 789KB to 416KB. Which is about 48% less than in the current state of the site. The Dortmund page from 1.1MB (!) to 237KB, a reduction of 78%.

**Suggestion:**
An approach like this maybe should be promoted in the handbooks/guidelines to keep the steadliy growing OTS website as slim and lightweight as possible.

### CODE REVIEW

**Comment by Ivoz** [comment]
This is destructively downsizing though, and doesn't account for screen resolutions increasing as time goes on. Are we just shafting macbook hdpi users?

A better method would be to realise that the images are currently majorly cropped when displayed on the website, although somewhat artistically. Although the cropping does allow for different screen ratios. Instead of downsizing the images and keeping the in-browser cropping, crop the images at source give them a uniform size ratio, and rejink the css.

**Comment by mbesser** [comment]
I absolutely agree with you, that we should have an eye on upcoming technology and it's capabilities. But in this case it might be appropriate to handle at least the existing image files like this because they aren't suitable for high resolution displays either.

**Comment by Ivoz** [comment]
> because they aren't suitable for high resolution displays either. 

why not?

**Comment by gnunicorn** [comment]
As we are doing the background images with CSS already, I would love to have different sizes used in a mobile-first-responsive manner. Say, we have a 320px version that is loaded per default but if any of the bigger screens matches, we adapt by scaling back up to our original size. (this goes along the principles of [responsejs](http://responsejs.com/) without actually having to add JS for it). That way we can make the footprint lower for mobile easily imho.

**Comment by mbesser** [comment]
I admit some of them are already okay for small high-res screens (but still too large in file size). But the dimensions of the majority of the images are not big enough to cater screens like Retina iPad or Macbooks with a decent image quality. They'd be scaled up which results in a visible quality loss nonetheless.

So i think it's an acceptable trade-off to serve some users with an okay-ish image quality and to show most users good image quality and finally to save them all a few (or some more) KB to download.

Btw: i've tested my changes on a retina iPhone, a very close to retina tablet and my nod so retina old macbook. Image quality was fine on each.

**Comment by mbesser** [comment]
@ligthyear Yes, this would be a more advanced and not-so-hacky approach compared to what i'm suggesting. If i understand right you are proposing that we should rather add responsejs? This would require some extra effort in the beginning but might pay off as soon it's completely implemented…

The approached i suggested worked good for me so far. Easy, quick, mostly good results but admittedly a bit dirty ;)

**Comment by gnunicorn** [comment]
@mbesser , no. Response.js is needed because for img-tags, you can't control it's source through css media queries. But as we are not using img-tag but already have the reference for the images in our CSS (as proper css-backgrounds). We could directly use media queries to offer different resolutions for different devices (or at least screen sizes) through that. It was always something in the back of my head but never got around actually implementing it.

**Comment by Ivoz** [comment]
I haven't heard of any technique for lowering image size by upscaling them. How does this work?

Otherwise I would recommend against all upscales.

**Comment by Ivoz** [comment]
Given the commonality, I think the best thing to do would be crop the large backgrounds to a 15:8 ratop as that is slightly lower than the most common ratio for those. It would allow them to look the same no matter the screen ratio used (after some css fixes).

I don't see the point in upscaling image sizes, but I'd support downsizing team photos to a uniform 400x400 when they are bigger.

**Comment by stefanhoth** [comment]
Can't we just use the (new) standard srcset? 

```
<img src="fallback.jpg" srcset="small.jpg 640w 1x, small-hd.jpg 640w 2x, large.jpg 1x, large-hd.jpg 2x" alt="…">
```

Native browser support is looking good already http://caniuse.com/#search=srcset

**Comment by Ivoz** [comment]
Closing this for now. I would be happy to discuss it again, but in two pull requests, to make them easy to discuss / accept: a) standardize member photo size b) standardize city background images

**Pull request closed without merging**
