### PR TITLE
More Handbooks: The Schedule of a Workshop Organiser

### PR DESCRIPTION
**Pull request by gnunicorn**
With plenty of example emails, best practices and stuff to say and do. And it makes sure the Learners meetup gets more visibility.

### CODE REVIEW

**Comment by gnunicorn** [comment]
Can I has review? Copyediting and/or Feedbackz?

//cc @aleksis , @beatricemartini , @stefanhoth , @stevenfarlie , @utstikkar , @sjockers

**Comment by stefanhoth** [comment]
@ligthyear Good job Ben. I read everything and it seems great. If there's anything missing we can fix it later on. Unless some else will comment until tomorrow I will merge it.

**Comment by gnunicorn** [comment]
@stefanhoth got someone to ask you for fixes or can we merge now?

**Comment by stefanhoth** [comment]
I didn't ask someone specific. Too late now, merged.

**Pull request merged**
