### PR TITLE
Better jekyll

### PR DESCRIPTION
**Pull request by lehmannro**
New Jekyll version, using the collections feature.

### CODE REVIEW

**Comment by lehmannro** [comment]
If there are no objections/comments by tomorrow EOD I'll merge.

**Comment by lehmannro** [comment]
@xMartin @gsambrotta

**Comment by gsambrotta** [comment]
I'm not an rails expert but code looks good. 
Also I couldn't try on my local so I don't know if everything works

**Comment by lehmannro** [comment]
Is there an error that prevented you from trying locally?

**Comment by gsambrotta** [comment]
nope, i just don't know how to check another fork form my terminal and
right now I don't have the time to figured out how to do it :)

On 23 April 2015 at 18:07, Robert Lehmann notifications@github.com wrote:

> Is there an error that prevented you from trying locally?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenTechSchool/www.opentechschool.org/pull/184#issuecomment-95635416
> .

## 

```
     [image: logo.png]   Giorgia Sambrotta
                              Web Design
```

E-mail: g.sambrotta@gmail.com

Web:  www.designbygio.it

Mobile: 0049 152.081.41.291  (Germany)

Twitter: @designbygio

**Comment by xMartin** [comment]
The new setup does not run with Ruby 1.9 anymore and this information is quite hard to find at the moment (https://github.com/github/pages-gem/issues/122). We should add a hint to the README.

**Comment by xMartin** [comment]
The chapter pages look different now for me (see screenshot),
scnreenshot berlin

**Comment by lehmannro** [comment]
Going to take a look tonight.

**Comment by lehmannro** [comment]
Meh, this was not introduced in this PR.  I have a stale Compass build from before all the _new UX_ madness and it works there;  when I rebuild with the _new UX_ changes I have the breakage you describe.  Tempted to just merge.

**Comment by lehmannro** [comment]
Hey @gsambrotta, I traced back the removal of the `text-align: center;` attribute to your `update-header-logo` branch.  I have reverted what I could identify as potentially harmful;  could you take another look?  I suppose especially the main page is not how you want it to be.

**Comment by Ivoz** [comment]
Nice use of that feature @lehmannro :)

**Pull request merged**
