### PR TITLE
Adding Bristol chapter

### PR DESCRIPTION
**Pull request by katjad**
Think have added all the things, just no email addresses for now - please check :)

### CODE REVIEW

**Comment by Ivoz** [comment]
Please don't delete our stylesheet!

(I think you might just need to regenerate it with compass)

I'd suggest doing a `git commit --amend` after fixing it and `git push --force` after to keep the history clean. Additionally a rebase would obviate the first commit (from 502bf5114eeaa4b825d7bf3620dfdedaf80cece4)

**Comment by katjad** [comment]
Oops sorry, I did not mean to delete it. I am on holiday so will not get to correct this very soon, but will do as soon as I get the opportunity.

Katja

**Comment by katjad** [comment]
Stylesheet is back. I did not do the rebase now, but I guess that's not essential?
Hope all okay now. And thanks for your help! 
Katja

**Comment by xMartin** [comment]
Is this still a thing?

**Comment by katjad** [comment]
Yes, it is. Just changed it slightly now.

**Comment by xMartin** [comment]
Cool! Thanks for your patience ;)

**Pull request merged**
