### PR TITLE
Update Berlin team

### PR DESCRIPTION
**Pull request by xMartin**

### CODE REVIEW

**Comment by ellenkoenig** [comment]
ots ellen

Ellen König
ellen@opentechschool.org

**Comment by lehmannro** [comment]
Please hold off with this PR, I'm currently preparing a switch to Jekyll collections and will get rid of `members.yml` while we go.  Should be ready EOW latest.

**Comment by lehmannro** [comment]
Good to go!  Anybody else or is it just @ellenkoenig?

**Comment by xMartin** [comment]
Obsolete by https://github.com/OpenTechSchool/www.opentechschool.org/pull/204

**Pull request closed without merging**
