### PR TITLE
Add chapter Brussels

### PR DESCRIPTION
**Pull request by friedger**

### CODE REVIEW

**Comment by gnunicorn** [comment]
I think there was another small bug in this one: it didn't show the background picture because that was missing from the sass/styles. I made an updated version of this here https://github.com/ligthyear/www.opentechschool.org/tree/brussels-review . Please review if those changes are what and how you want to have it and if so, I'm happy to merge.

**Comment by Ivoz** [comment]
@ligthyear I added a PR for your changes to @friedger's branch, which when merged should appear on this PR. Good spotting for the missing css.

**Comment by friedger** [comment]
Pull request merged :-) So this PR could get into the main one.

**Comment by Ivoz** [comment]
Can you tell me if jekyll builds this branch now correctly? Just wondering, without `emails` fields in some members whether it hiccups or skips/ignores.

**Comment by gnunicorn** [comment]
@Ivoz , yes compiles fine here. Merging.

**Comment by Ivoz** [comment]
Hugo has no image :(

http://www.opentechschool.org/brussels/

**Pull request merged**
