### PR TITLE
[WIP] romagna chapter page

### PR DESCRIPTION
**Pull request by xMartin**
TODO

- [x] add tagline
- [x] update description
- [x] decide for image (+ attribution)
- [x] add members to discourse group "TeamRomagna"

### CODE REVIEW

**Comment by xMartin** [comment]
Image is from here: https://it.wikipedia.org/wiki/Romagna#/media/File:Tiberius-Br%C3%BCcke.JPG
If we want to keep it, it might need attribution.

**Comment by xMartin** [comment]
@gsambrotta can you ping the romagna folks to take this over?

**Review by fhuel — COMMENTED** [review]
Everything's fine I guess, thanks.
I'll proceed to write some more specific info the About.
And I'd probably would use a picture from Cesena, like this one : http://www.womeninrun.it/wp-content/uploads/2016/01/Cesena.jpg

**Comment by xMartin** [comment]
@fhuel Cool, you should have permissions now to take over. Let me know if you need support. Please make sure we have permission to use the image.

**Comment by xMartin** [comment]
Hey, it would be super nice to get this done and show the world this chapter :)

**Comment by fhuel** [comment]
Hey,
it should be ok now.

The attribution for the picture is :
By Fabrizio Pasi (Own work) [CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0)], via Wikimedia Commons

Please let me know if everything's fine

Thanks :)

**Comment by xMartin** [comment]
Nice!

There‘s a typo in the description („culture“).

And can you  add the attribution to the imprint page?

There‘s also a merge conflict.

**Comment by fhuel** [comment]
Is this ok?

**Comment by xMartin** [comment]
Nice! But you have to remove the `redirect_to` property in the file header to make the link to the page actually work.

**Comment by fhuel** [comment]
Ok, I think I did it.
Is it working fine now?

**Comment by xMartin** [comment]
It’s still redirecting to the meetup page. I cannot see a change.

**Comment by fhuel** [comment]
oh gosh, sorry.
I removed the redirect_to now

**Comment by xMartin** [comment]
👍 Gracie

**Pull request merged**
