### PR TITLE
Improve code of conduct

### PR DESCRIPTION
**Pull request by xMartin**
Removed conferences in favor of events. And consistent American English...

### CODE REVIEW

**Comment by xMartin** [comment]
I know it's a tiny change but would love to get some +1 from event organizers.

@ligthyear @ellenkoenig @skade @Ivoz @lehmannro

**Comment by lehmannro** [comment]
:+1:

I can understand why the orginal CoC chose _“contributors”_ — it makes it clear the statement applies to both, organizers and attendees, and that both can have the same impact on the event.  I'm not too attached to word-smithing in a dead document, so either choice is fine by me.

**Comment by ellenkoenig** [comment]
👍 Looks like an improvement to me

**Comment by skade** [comment]
👍 I like it.

**Pull request merged**
